using Affiliance_core.ApiHelper;
using Affiliance_core.Dto.TrackingLinkDto;
using Affiliance_core.interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Affiliance_Api.Controllers
{
    /// <summary>
    /// Controller for managing tracking links for marketers.
    /// </summary>
    [Route("api/marketer")]
    [ApiController]
    public class TrackingLinkController : ControllerBase
    {
        private readonly IServicesManager _servicesManager;

        public TrackingLinkController(IServicesManager servicesManager)
        {
            _servicesManager = servicesManager;
        }

        /// <summary>
        /// Retrieves tracking links generated by the authenticated marketer.
        /// </summary>
        /// <param name="filter">Filter criteria regarding campaign and active status.</param>
        /// <returns>Returns a paginated list of tracking links.</returns>
        [HttpGet("my/tracking-links")]
        [Authorize(Roles = "Marketer")]
        [ProducesResponseType(typeof(ApiResponse<PagedResult<TrackingLinkDto>>), StatusCodes.Status200OK)]
        public async Task<IActionResult> GetMyTrackingLinks([FromQuery] TrackingLinkFilterDto? filter)
        {
            var marketerId = GetMarketerId();
            if (marketerId == 0)
                return Unauthorized();

            var result = await _servicesManager.TrackingLinkService.GetTrackingLinksAsync(marketerId, filter);
            if (!result.Success)
                return BadRequest(result);
            return Ok(result);
        }

        /// <summary>
        /// Retrieves a specific tracking link by its ID.
        /// </summary>
        /// <param name="linkId">The ID of the tracking link.</param>
        /// <returns>Returns the detailed information of the tracking link.</returns>
        [HttpGet("my/tracking-links/{linkId}")]
        [Authorize(Roles = "Marketer")]
        [ProducesResponseType(typeof(ApiResponse<TrackingLinkDto>), StatusCodes.Status200OK)]
        public async Task<IActionResult> GetTrackingLinkById(int linkId)
        {
            var marketerId = GetMarketerId();
            if (marketerId == 0)
                return Unauthorized();

            var result = await _servicesManager.TrackingLinkService.GetTrackingLinkByIdAsync(linkId, marketerId);
            if (!result.Success)
                return NotFound(result);
            return Ok(result);
        }

        /// <summary>
        /// Retrieves statistics for a specific tracking link.
        /// </summary>
        /// <param name="linkId">The ID of the tracking link.</param>
        /// <returns>Returns statistics including clicks, conversions, and earnings for the link.</returns>
        [HttpGet("my/tracking-links/{linkId}/statistics")]
        [Authorize(Roles = "Marketer")]
        [ProducesResponseType(typeof(ApiResponse<TrackingLinkStatisticsDto>), StatusCodes.Status200OK)]
        public async Task<IActionResult> GetTrackingLinkStatistics(int linkId)
        {
            var marketerId = GetMarketerId();
            if (marketerId == 0)
                return Unauthorized();

            var result = await _servicesManager.TrackingLinkService.GetTrackingLinkStatisticsAsync(linkId, marketerId);
            if (!result.Success)
                return NotFound(result);
            return Ok(result);
        }

        private int GetMarketerId()
        {
            var marketerId = User.FindFirst("marketerId")?.Value;
            return int.TryParse(marketerId, out var id) ? id : 0;
        }
    }
}
